version: '3.9'

services:
  redis_sentinel_server_tls:
    container_name: redis-sentinel-tls
    image: redis:${REDIS_TAG}
    volumes:
      - ../../apps/emqx/etc/certs/cacert.pem:/etc/certs/ca.crt
      - ../../apps/emqx/etc/certs/cert.pem:/etc/certs/redis.crt
      - ../../apps/emqx/etc/certs/key.pem:/etc/certs/redis.key
      - ./redis/:/data/conf
    command: bash -c "/bin/bash /data/conf/redis.sh --node sentinel --tls-enabled && tail -f /var/log/redis-server.log"
    networks:
      - emqx_bridge
